FROM nginx:1.15.12

ARG RAILS_ROOT=/app
WORKDIR $RAILS_ROOT
RUN mkdir log
COPY public public/

COPY website.com.conf /tmp/docker.nginx

RUN envsubst '$RAILS_ROOT' < /tmp/docker.nginx > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
